# A Reminder from the Fenway Victory Gardens 
## 8 – 10 May 2026

The gift of joyful labour in the morning hours has once again been bringing me to the edge of the working day quite early, leaving an almost uncomfortable amount of time for leisure in the afternoons. My second university reading and final examination period has been marked with reflection and planning as much as it has been used to explore the lands surrounding Cambridge. This past Tuesday afternoon, I travelled to the Back Bay Fens beyond the southeastern edge of the former Shawmut Peninsula. The relatively serene parkland sits just before the continuous greenery of the Emerald Necklace is channelled underneath Interstate 90 and into the Charles River Esplanade. Indeed, the idea that the Emerald Necklace can be followed to places as far (yet still heavily developed) as Franklin Park without interruption remains captivating. In the last relatively spacious expanse of this corridor lie the oldest WWII victory gardens in continual use. I found myself in the midst of the labyrinthine pathways of the Richard D. Parker Memorial Victory Gardens when—even if for a moment under the May afternoon sun—a certain disconnection with the earth struck me with a melange of comfort and concern.

Gardening is one of the most wholesome seasonal hobbies for the mind and the body, which is likely why I have written so extensively about the garden in years prior. The first breaking of the ground at my home last March marks the moment when a deeper appreciation for the garden came upon me, however, an appreciation beyond the bliss of working in the relative cold of that spring Sunday. My toils on that small plot of land were largely out of leisure, and I explicitly recall writing of the blessed state I was in to till the ground with so light of consequence on that day of rest. Nevertheless, the garden is a microcosm of what has occupied most people for most of human history.

To sink one’s time and thoughts into the plants that one fathers on a particular piece of land is to foster a living link with times now long past. It also provides innumerable rewards in the present. I have come to recognise the vegetables that I consume as organisms (or pieces thereof) whose life cycles manifest visibly throughout the growing season. Beetroot is a biennial plant, for example, meaning that one growing it for food must leave a portion of his crops so that they may overwinter. Only these second-year beet plants will flower and produce a copious number of seeds—a number of future beetroot crops that pays off for the then-inedible roots with incalculable interest. This awareness of where one’s fundamental sustenance is sourced as an end-user of modern industrial society is a matter that I will not diverge into here. I will only add that it applies no less consequentially to meat. Limiting one’s consumption of meat to the rough frequency of those who lived in agrarian societies of centuries past—perhaps to the vegetable-based diet of a typical medieval English field labourer—is a most enjoyable and wholesome practice. Michael Pollan’s *[The Omnivore’s Dillema](https://michaelpollan.com/books/the-omnivores-dilemma/)* touches upon a similar pleasure in knowing what one is eating; it is a reading that I highly recommend. I dare add that Pollan’s writing may even lead some to eat meat with greater confidence.

Returning to the victory gardens in the midst of the urban immensity of Boston, the sight and smell of bare soil that afternoon brought forth the idea of the garden viewed through another lens. Working the earth allows one to experience a hint of the completely different world that people in the distant past inhabited. A summer afternoon spent in the rows of a garden is akin to an excursion into times of yore. This is one of many reasons why gardening is not a thoughtless activity. The serenity that I have found weeding between rows of beans is likewise the result of careful planning and more laborious maintenance. Inevitably falling back onto the produce of industrial agriculture lowers the stakes of this care, however, which made itself evident on that afternoon. I remain a long distance from my home garden, whose soil I have been unable to work this year. More generally, the distance between me and the steadfast connection a yeoman farmer of the 16th century would have with the May soil spurred a dual comfort and helplessness. The fact that the garden remains a timeless way to work the earth, as even the non-utilitarian plots of garden landscaping reminded me, evokes the former. The fact that I—or almost any other modern industrial end-user—will likely never be able to accumulate enough time and knowledge to sustain himself off the land like his forefathers evokes the latter. As my own plans for sowing as soon as I return home evidence, however, the garden may always bring me closer.

I have long yearned to master the cultivation of staple crops, namely wheat and other grains. As one who receives most of his carbohydrates from wheat and corn, it is almost an obligation that I read the reputable *[Small-Scale Grain Raising](https://www.chelseagreen.com/product/small-scale-grain-raising/)* as soon as I return home later this May. I will be reading with the possibility of sowing in mind, as late it may already be in the season (I am finding the maxim to wait until Memorial Day for the last danger of frost ring ever shallower this year). My attempt to grow spring einkorn wheat last year only evidenced why winter wheat varieties have historically been planted. These varieties are sowed in the late fall so that the grasses may establish themselves. They emerge in the spring with a pre-established root system and a vigour that outcompetes weeds. I have more recently resolved to grow the “bitter herbs” of the [“Maror”](https://en.wikipedia.org/wiki/Maror) that would have been available in the ancient near east. Beyond what is perhaps an even more compelling “link to the past,” growing ancient varieties of these plants in the modern day seems in itself to be a rewarding endeavour.

The garden nevertheless enables one to perceive the land around him in a manner that walking or hiking cannot reproduce alone. Spending focused time in a particular piece of land may make that piece of land part of one’s home, bringing forth all of its nuances and familiarity. Yet spending this time with intention often enriches the appreciation of one’s surroundings. That is why foraging in the natural environment, arguably an even more timeless practice, has constituted a new resolve of mine. Partly for its value as a practical and potentially life-saving skill, partly out of an appreciation for one’s fundamental sources of sustenance, and partly out of familiarising oneself with the land in a deeper manner, foraging for food may be another wholesome yet hidden way to spend hours of leisure.

I will be attempting to forage this summer. I may be collecting and processing the invasive garlic mustard as soon as this last week that I will be Massachusetts until late August. My suspicions of the white-flowered shoots—ones that resembled the images on a warning I saw posted on the Allegheny National Forest web site long ago—growing in patches throughout almost every natural space I have visited in recent weeks were confirmed after brief internet research. I will end this entry by noting three resources that I have found particularly useful in building my confidence for a potential forage. From the intense cultivation of the garden to the wilderness free from human hands, knowledge like this brings one incrementally closer to the seemingly impossible task of deriving sustenance from the land.

[JSTOR Plant of the Month: Garlic Mustard]( https://daily.jstor.org/plant-of-the-month-garlic-mustard/)

[Invasive Plants in Massachusetts: Garlic Mustard (Mass Audubon)]( https://www.massaudubon.org/nature-wildlife/invasive-plants-in-massachusetts/garlic-mustard)

[Garlic Mustard, a Ubiquitous Invasive Weed (PennState Extension)]( https://extension.psu.edu/garlic-mustard-a-ubiquitous-invasive-weed) 
